dist: trusty

language: scala
scala:
 - 2.12.6

branches:
 only:
  - master

jdk:
#  - oraclejdk8
#  - oraclejdk9
  - oraclejdk10      

cache:
  directories:
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt/boot/'

script:
  - sbt clean coverage test
  - sbt coverageReport
  - sbt coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - CODACY_PROJECT_TOKEN="68d05476268f4e24bee35afae04eda12" sbt codacyCoverage
