dist: trusty

language: scala
scala:
 - 2.12.6

#branches:
# only:
#  - master

#before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
- jdk:
  - oraclejdk10

#install:
#  - wget https://download.java.net/java/GA/jdk10/10/binaries/openjdk-10_linux-x64_bin.tar.gz
#  - tar -xzf openjdk-10_linux-x64_bin.tar.gz
#  - export JAVA_HOME=$(pwd)/jdk-10

cache:
  directories:
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt/boot/'

script:
  - sbt clean coverage test coverageReport
  - sbt coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - CODACY_PROJECT_TOKEN="68d05476268f4e24bee35afae04eda12" sbt codacyCoverage
